import { createHash } from "node:crypto";

export const ALLOWED_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".java", ".py"]);

export const EXCLUDED_PATH_SEGMENTS = [
  "node_modules/",
  "dist/",
  "build/",
  ".next/",
  "coverage/",
  "__generated__/",
  ".min.js",
  "__pycache__/",
  ".venv/",
  "venv/",
  "migrations/", // Django's autogenerated migration files -- repetitive boilerplate, near-zero retrieval value
];

/** Shared across every code connector so ingestibility rules stay consistent regardless of provider. */
export function isIngestible(path: string): boolean {
  const ext = path.slice(path.lastIndexOf("."));
  if (!ALLOWED_EXTENSIONS.has(ext)) return false;
  if (EXCLUDED_PATH_SEGMENTS.some((seg) => path.includes(seg))) return false;
  // Skip test/spec files by default -- flip this if you want test code indexed too.
  if (/\.(test|spec)\.[jt]sx?$/.test(path)) return false;
  const baseName = path.slice(path.lastIndexOf("/") + 1);
  if (/^test_.*\.py$/.test(baseName) || /_test\.py$/.test(baseName)) return false;
  return true;
}

export function hashContent(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

export function languageForPath(path: string): string {
  if (path.endsWith(".java")) return "java";
  if (path.endsWith(".py")) return "python";
  return path.endsWith(".tsx") || path.endsWith(".ts") ? "typescript" : "javascript";
}
